buy_me_a_coffee: namelessnanashi
github: NanashiTheNameless
ko_fi: nanashithenameless
thanks_dev: u/gh/nanashithenameless
custom:
  - "https://www.paypal.me/NamelessNanashi"
  - "https://throne.com/namelessnanashi"
